/**
 * Loads the fictional demo dataset so you can click around a populated app.
 *
 * Everything it creates is marked `source = 'demo'` and every company name ends
 * in "(Demo)". Phone numbers come from Ofcom's reserved drama/fiction ranges,
 * so nothing in here can dial a real business. Remove it all with --purge.
 */
import fs from 'node:fs';
import path from 'node:path';
import { getDb } from '../db/index.js';
import { repoRoot } from '../lib/env.js';
import { recordCall, recordTestCall } from '../domain/leads.js';
import { rescoreAll } from '../domain/scoring-store.js';
import { importCsv } from '../ingest/csv-import.js';
import type { CallOutcome, TestCallOutcome } from '../domain/types.js';
import { flagBool, parseArgs } from './args.js';

const args = parseArgs();
const db = getDb();

if (flagBool(args, 'purge')) {
  const removed = db.prepare("DELETE FROM leads WHERE source = 'demo'").run().changes;
  console.log(`Removed ${removed} demo lead(s).`);
  db.close();
  process.exit(0);
}

const csvPath = path.resolve(repoRoot, 'sample-data/demo-leads.csv');
if (!fs.existsSync(csvPath)) {
  console.error(`Demo CSV not found at ${csvPath}`);
  process.exit(1);
}

const report = importCsv(db, fs.readFileSync(csvPath, 'utf8'), {
  filename: 'demo-leads.csv',
  source: 'demo',
});
console.log(`Imported demo data: ${report.created} created, ${report.updated} updated, ${report.skipped} skipped.`);

// --- A plausible slice of manual activity, so the dashboard is not empty -----
const leads = db
  .prepare("SELECT id FROM leads WHERE source = 'demo' ORDER BY score DESC")
  .all() as Array<{ id: number }>;

const testOutcomes: Array<[TestCallOutcome, Partial<{ out_of_hours: boolean; poor_handling: boolean; ring_seconds: number }>]> = [
  ['no_answer', { out_of_hours: true, ring_seconds: 45 }],
  ['voicemail', { ring_seconds: 22 }],
  ['answered_human', { ring_seconds: 6 }],
  ['no_answer', { ring_seconds: 40 }],
  ['automated_receptionist', { poor_handling: true, ring_seconds: 12 }],
  ['voicemail', { out_of_hours: true, ring_seconds: 18 }],
  ['human_receptionist', { ring_seconds: 8 }],
  ['engaged', { ring_seconds: 3 }],
];

const salesOutcomes: CallOutcome[] = [
  'no_answer', 'voicemail', 'gatekeeper', 'owner_reached', 'interested',
  'not_interested', 'follow_up_required', 'demo_booked', 'customer',
];

let tested = 0;
let called = 0;

// Roughly half get a test call; a third of those get a sales call logged.
leads.forEach((lead, index) => {
  if (index % 2 !== 0) return;
  const [outcome, extras] = testOutcomes[index % testOutcomes.length]!;
  const daysAgo = (index % 12) + 1;
  const hour = extras.out_of_hours ? 19 + (index % 3) : 10 + (index % 6);
  const attemptedAt = new Date(Date.now() - daysAgo * 86_400_000);
  attemptedAt.setHours(hour, (index * 7) % 60, 0, 0);

  recordTestCall(db, lead.id, { outcome, attempted_at: attemptedAt.toISOString(), ...extras });
  tested += 1;

  if (index % 6 !== 0) return;
  const salesOutcome = salesOutcomes[(index / 6) % salesOutcomes.length]!;
  const calledAt = new Date(Date.now() - ((index % 9) + 1) * 86_400_000);
  const followUp =
    salesOutcome === 'interested' || salesOutcome === 'follow_up_required' || salesOutcome === 'gatekeeper'
      ? new Date(Date.now() + (((index % 5) - 2) * 86_400_000)).toISOString().slice(0, 10)
      : null;

  recordCall(db, lead.id, {
    outcome: salesOutcome,
    called_at: calledAt.toISOString(),
    notes: 'Demo call record — generated by seed:demo.',
    follow_up_date: followUp,
    follow_up_notes: followUp ? 'Call back and ask about after-hours cover.' : null,
    next_action: followUp ? 'Call back' : null,
    contract_value: salesOutcome === 'customer' ? 149 : null,
  });
  called += 1;
});

const rescored = rescoreAll(db);
const priority = db.prepare("SELECT COUNT(*) AS n FROM leads WHERE score_band = 'Priority'").get() as { n: number };

console.log(`Logged ${tested} test call(s) and ${called} sales call(s).`);
console.log(`Rescored ${rescored.scored} lead(s); ${priority.n} are Priority.`);
console.log(`\nStart the app with: npm run dev`);
console.log(`Remove this data with: npm run seed:demo -- --purge`);

db.close();
